menu:
  首页: /
  归档: /archives

widgets:
- search
- category
- tag

excerpt_link: 详细
fancybox: true
rss: /atom.xml

#分享插件
share_provider: baidu

##addthis插件
share_addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: false
  pinterest: false

##baidu分享定制的太多，直接拷贝代码到 layout/share/baidu.ejs里面

twitter:
  username: 
  show_replies: false
  tweet_count: 5


#评论插件
comment_provider: duoshuo

##Facebook comment
comment_facebook:
  appid: 123456789012345
  comment_count: 5
  comment_width: 840
  comment_colorscheme: light

##多说评论组件
comment_duoshuo: 
  short_name: 

google_analytics: